[package]
name = "manix-cli"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
manix = { path = "/home/clark/code/personal/manix" }
tokio = { version = "1", features = ["full"] }
